// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpOVdUXEWW3u09ShqRLdYkTJonzSjSeAg',
    appId: '1:548887080938:web:5dc8f5c6eb8bdc6eea0c93',
    messagingSenderId: '548887080938',
    projectId: 'study-app-2d032',
    authDomain: 'study-app-2d032.firebaseapp.com',
    storageBucket: 'study-app-2d032.firebasestorage.app',
    measurementId: 'G-T75FW4ZVJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFehebquhuOI1GrF8lbASAuNufrXnd8k0',
    appId: '1:548887080938:android:33aef21073319924ea0c93',
    messagingSenderId: '548887080938',
    projectId: 'study-app-2d032',
    storageBucket: 'study-app-2d032.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0O8ug9OCvwNTNdbKMKr57eNXOXWnKwgc',
    appId: '1:548887080938:ios:881991f719905f17ea0c93',
    messagingSenderId: '548887080938',
    projectId: 'study-app-2d032',
    storageBucket: 'study-app-2d032.firebasestorage.app',
    iosClientId: '548887080938-1j821u5cpnglttbudeh169s7pjelt7sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentAcademicAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0O8ug9OCvwNTNdbKMKr57eNXOXWnKwgc',
    appId: '1:548887080938:ios:881991f719905f17ea0c93',
    messagingSenderId: '548887080938',
    projectId: 'study-app-2d032',
    storageBucket: 'study-app-2d032.firebasestorage.app',
    iosClientId: '548887080938-1j821u5cpnglttbudeh169s7pjelt7sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentAcademicAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpOVdUXEWW3u09ShqRLdYkTJonzSjSeAg',
    appId: '1:548887080938:web:402cd562a866e720ea0c93',
    messagingSenderId: '548887080938',
    projectId: 'study-app-2d032',
    authDomain: 'study-app-2d032.firebaseapp.com',
    storageBucket: 'study-app-2d032.firebasestorage.app',
    measurementId: 'G-42NP6FXQPB',
  );
}
